Repository rl-institut/oemof-B3, pull requests merged in 2023-09, with the labels that each got.

#341 Fix by adapting output path handling
  scripts/plot_conv_pp_scalars.py
Labels: bug

#342 Add oem2orm to poetry
  poetry.lock
  pyproject.toml
Labels: bug

#343 Features/improve log filepath
  scripts/optimize.py
Labels: enhancement

#337 Replace deprecated op parameter with predicate
  oemof_b3/tools/geo.py
Labels: enhancement

#327 Feature/revise docs
  README.md
  docs/bibliography.bib
  docs/getting_started.rst
  docs/how_to_customize_oemof-B3.rst
  docs/model_pipeline.rst
  docs/whats_new.rst
  oemof_b3/tools/geo.py
Labels: documentation
